# Generated by Django 6.0.6 on 2026-06-05 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='unique_response_per_user_per_survey'),
        ),
    ]
