# Generated by Django 6.0.6 on 2026-06-05 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_user_fields_to_profile(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('users', 'Profile')

    for user in User.objects.all():
        Profile.objects.update_or_create(
            user=user,
            defaults={
                'bio': getattr(user, 'bio', '') or '',
                'avatar': getattr(user, 'avatar', '') or '',
                'phone': getattr(user, 'phone', '') or '',
            },
        )


def reverse_copy_profile_to_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('users', 'Profile')

    for profile in Profile.objects.select_related('user').all():
        user = profile.user
        user.bio = profile.bio
        user.avatar = profile.avatar
        user.phone = profile.phone
        user.save(update_fields=['bio', 'avatar', 'phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.RunPython(copy_user_fields_to_profile, reverse_copy_profile_to_user),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
